project_id = "qkiradbwrajrqgnyjhvd"

[functions.sync-fixtures]
verify_jwt = false

[functions.sync-odds]
verify_jwt = false

[functions.generate-picks]
verify_jwt = false

[functions.settle-results]
verify_jwt = false
